In [7]:
import numpy as np

a = np.array([[3.2, 4.0], [2.4, 6.2]])
print(a)
print("shape: ",  a.shape)
print("size: ", a.size)
print("dtype: ", a.dtype)
print("ndim: ", a.ndim)


[[3.2 4. ]
 [2.4 6.2]]
shape:  (2, 2)
size:  4
dtype:  float64
ndim:  2


In [10]:
zeros = np.zeros((2,2))
zeros


In [16]:
ones = np.ones((3,5,3),  dtype="float32")
ones 

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)

In [22]:
fill_value = 3
full = np.full((3,3,3),fill_value,  dtype="int64")
full

array([[[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]]])

In [23]:
a = np.arange(3, 30, 3)
a

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [25]:
b = np.linspace(5, 100)
b

array([  5.        ,   6.93877551,   8.87755102,  10.81632653,
        12.75510204,  14.69387755,  16.63265306,  18.57142857,
        20.51020408,  22.44897959,  24.3877551 ,  26.32653061,
        28.26530612,  30.20408163,  32.14285714,  34.08163265,
        36.02040816,  37.95918367,  39.89795918,  41.83673469,
        43.7755102 ,  45.71428571,  47.65306122,  49.59183673,
        51.53061224,  53.46938776,  55.40816327,  57.34693878,
        59.28571429,  61.2244898 ,  63.16326531,  65.10204082,
        67.04081633,  68.97959184,  70.91836735,  72.85714286,
        74.79591837,  76.73469388,  78.67346939,  80.6122449 ,
        82.55102041,  84.48979592,  86.42857143,  88.36734694,
        90.30612245,  92.24489796,  94.18367347,  96.12244898,
        98.06122449, 100.        ])

In [58]:
f_arr = np.arange(1,5,1).reshape((2,2))
f_arr_2 = np.arange(5,9,1).reshape((2,2))

print(f_arr)
print(f_arr_2)
print(np.exp(f_arr))
print(np.sqrt(f_arr_2))

print(np.sum(f_arr, axis=1))
print(np.mean(f_arr, axis=1))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]
[3 7]
[1.5 3.5]


## Indexing & views vs copies
Create small matrices and complete the following exercises:

In [76]:
test = np.arange(1,13,1).reshape(3,4)
print(test[:2,:2])

mask = test > 6
print(mask)

test[mask] = -1
print(test)

[[1 2]
 [5 6]]
[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[[ 1  2  3  4]
 [ 5  6 -1 -1]
 [-1 -1 -1 -1]]
